# Generated by Django 3.2.18 on 2023-05-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
