# Generated by Django 3.2.18 on 2023-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
