# Generated by Django 3.2.18 on 2023-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_appointment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
